services:
  appointmentrest.webapi:
    image: appointments-rest-microservice
    build:
      context: .
      dockerfile: AppointmentREST.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=env
      - JWT_SigningKey=key
      - NEON_DB_PASSWORD=password

  
