services:
  appointmentrest.webapi:
    image: appointmentrest.webapi
    build:
      context: .
      dockerfile: AppointmentREST.WebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Container
    ports:
      - 8085:8080
  
